config/routes.rb
Rails.application.routes.draw do
  root "pages#index"
  get "/about", to: "pages#about"
  get "/pricing", to: "pages#pricing"
  get "/payment", to: "pages#payment"
  post "/checkout", to: "pages#checkout"

  namespace :api do
    namespace :v2 do
      resources :boards, only: [:index]
    end
  end

  resources :favorites, only: [:index]

  resources :boards do
    member do
      post :favorite
      put :hide
    end

    resources :posts, shallow: true do
      resources :comments, shallow: true, only: [:create]
    end
  end

  resources :users, only: [:create] do
    collection do
      get :sign_up
      get :edit
      patch :update
      get :sign_in
      post :login
      delete :sign_out
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/user.rb
class User < ApplicationRecord
  validates :account, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  before_create :encrypt_password

  has_many :board_masters
  has_many :boards, through: :board_masters
  has_many :posts
  has_many :comments

  has_many :favorite_boards
  has_many :favorited_boards, through: :favorite_boards, source: :board

  def self.login(options)
    if options[:account] && options[:password]
      find_by(account: options[:account],
              password: Digest::SHA1.hexdigest("x" + options[:password] + "y"))
    end
  end

  def toggle_favorite_board(b)
    if favorited_boards.exists?(b.id)
      favorited_boards.destroy(b)
    else
      favorited_boards << b
    end
  end

  private
  def encrypt_password
    self.password = bigbang(self.password)
  end

  def bigbang(string)
    string = "x" + string + "y"
    Digest::SHA1.hexdigest(string)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def sign_in
    @user = User.new
  end

  def login
    user = User.login(user_params)

    if user
      sign_in_user(user)
      redirect_to root_path, notice: "成功登入"
    else
      redirect_to sign_in_users_path, notice: "請輸入正確帳號密碼"
    end
  end

  def sign_up
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      # 登入
      sign_in_user(@user)
      redirect_to root_path, notice: '會員註冊成功'
    else
      render :sign_up
    end
  end

  def sign_out
    sign_out_user
    redirect_to root_path, notice: '登出成功'
  end

  private
  def sign_in_user(u)
    session[:user_token] = u.id
  end

  def sign_out_user
    session[:user_token] = nil
  end

  def user_params
    params.require(:user).permit(:account, :password, :email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/sign_in.html.erb
<h1>會員登入</h1>

<%= form_for(@user, url: login_users_path) do |form| %>
  <div class="fields">
    <%= form.label :account %>
    <%= form.text_field :account, placeholder: '請輸入帳號或 email' %>
  </div>

  <div class="fields">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <%= form.submit "登入" %>
<% end %>

app/views/users/sign_up.html.erb
<h1>會員註冊</h1>

<%= form_for(@user) do |form| %>
  <div class="fields">
    <%= form.label :account, "帳號" %>
    <%= form.text_field :account %>
  </div>

  <div class="fields">
    <%= form.label :password, "密碼" %>
    <%= form.password_field :password %>
  </div>

  <div class="fields">
    <%= form.label :email, "信箱" %>
    <%= form.email_field :email %>
  </div>

  <%= form.submit "註冊帳號" %>
<% end %>