config/routes.rb
Rails.application.routes.draw do
  root "pages#index"
  get "/about", to: "pages#about"
  get "/pricing", to: "pages#pricing"
  get "/payment", to: "pages#payment"
  post "/checkout", to: "pages#checkout"

  namespace :api do
    namespace :v2 do
      resources :boards, only: [:index]
    end
  end

  resources :favorites, only: [:index]

  resources :boards do
    member do
      post :favorite
      put :hide
    end

    resources :posts, shallow: true do
      resources :comments, shallow: true, only: [:create]
    end
  end

  resources :users, only: [:create] do
    collection do
      get :sign_up
      get :edit
      patch :update
      get :sign_in
      post :login
      delete :sign_out
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/board.rb
class Board < ApplicationRecord
  acts_as_paranoid
  paginates_per 6

  has_many :posts

  has_many :board_masters
  has_many :users, through: :board_masters

  has_many :favorite_boards
  has_many :favorited_users, through: :favorite_boards, source: :user

  validates :title, presence: true, length: { minimum: 2 }

  def favorited_by?(u)
    favorited_users.include?(u)
  end

  include AASM

  aasm(column: 'state') do
    state :normal, initial: true
    state :hidden, :locked

    event :hide do
      transitions from: [:normal, :locked], to: :hidden
    end

    event :show do
      transitions from: :hidden, to: :locked
    end

    event :lock do
      transitions from: [:normal, :hidden], to: :locked
    end

    event :unlock do
      transitions from: :locked, to: :normal
    end
  end
end

app/controllers/api/v2/boards_controller.rb
class Api::V2::BoardsController < ApplicationController
  def index
    @boards = Board.all
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :find_board, only: [:favorite, :show, :edit, :update, :destroy, :hide]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @boards = Board.normal.page(params[:page])
  end

  def show
    @posts = @board.posts.includes(:user)
  end

  def favorite
    current_user.toggle_favorite_board(@board)

    respond_to do |format|
      format.html { redirect_to favorites_path, notice: 'OK!' }
      format.json { render json: {status: @board.favorited_by?(current_user) } }
    end
  end

  def new
    @board = Board.new
    authorize @board, :new?
  end

  def create
    @board = Board.new(board_params)
    @board.users << current_user
    authorize @board, :create?

    if @board.save
      redirect_to boards_path, notice: "新增成功"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @board.update(board_params)
      redirect_to boards_path, notice: "更新成功"
    else
      render :edit
    end
  end

  def destroy
    @board.destroy
    redirect_to boards_path, notice: "刪除成功"
  end

  def hide
    @board.hide! if @board.may_hide?
    redirect_to boards_path, notice: '看版己隱藏'
  end

  private
  def find_board
    @board = Board.normal.find(params[:id])
  end

  # Strong Parameters
  def board_params
    params.require(:board).permit(:title, :intro)
  end
end

app/helpers/api/v2/boards_helper.rb
module Api::V2::BoardsHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
  def display_bm(board)
    if board.users.count == 0
      "徵求中"
    else
      board.users.map { |user| user.account }.join("/")
    end
  end
end

app/views/boards/_form.html.erb
<% if board.errors.any? %>
  <ul>
  <% board.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

<%= form_for(board) do |f| %>
  <div class="fields">
    <%= f.label :title, "看板名稱" %>
    <%= f.text_field :title %>
  </div>

  <div class="fields">
    <%= f.label :intro, "看板說明" %>
    <%= f.text_area :intro %>
  </div>

  <%= f.submit "送出" %>
<% end %>

app/views/boards/edit.html.erb
<h1>編輯看板</h1>

<%= render 'form', board: @board %>

app/views/boards/index.html.erb
<h1>看板</h1>

<%= link_to "新增看版", new_board_path if policy(:board).create? %>

<ul>
  <% @boards.each do |board| %>
    <li>
      <%= link_to board.title, board_path(board) %>
      <%= link_to "編輯", edit_board_path(board) %>
      <%= link_to "刪除", board_path(board), method: 'delete',
                          data: { confirm: '確認刪除?' } %>
      <%= link_to "隱版", hide_board_path(board), method: 'put' %>
    </li>
  <% end %>
</ul>
<%= paginate @boards %>

app/views/boards/new.html.erb
<h1>新增看板</h1>

<%= render 'form', board: @board %>

app/views/boards/show.html.erb
<h1 data-controller="heart" data-heart-board="<%= @board.id %>">
  看板 <%= @board.title %>
  <button data-action="click->heart#favorite">
    <% if @board.favorited_by?(current_user) %>
      <i class="fas fa-heart" data-target="heart.heart"></i>
    <% else %>
      <i class="far fa-heart" data-target="heart.heart"></i>
    <% end %>
  </button>
</h1>

<div>
  [版主：<%= display_bm(@board) %>]
</div>

<%= link_to "新增文章", new_board_post_path(@board) %>

<ul>
<% @posts.each do |post| %>
  <li data-controller="post" data-action="cat@window->post#something">
    <%= post.display_username %>
    <%= link_to post.title, post, data: { target: 'post.title' } %>
    <%= link_to "編輯", edit_post_path(post) %>
  </li>
<% end %>
</ul>