config/routes.rb
Rails.application.routes.draw do
  root "pages#index"
  get "/about", to: "pages#about"
  get "/pricing", to: "pages#pricing"
  get "/payment", to: "pages#payment"
  post "/checkout", to: "pages#checkout"

  namespace :api do
    namespace :v2 do
      resources :boards, only: [:index]
    end
  end

  resources :favorites, only: [:index]

  resources :boards do
    member do
      post :favorite
      put :hide
    end

    resources :posts, shallow: true do
      resources :comments, shallow: true, only: [:create]
    end
  end

  resources :users, only: [:create] do
    collection do
      get :sign_up
      get :edit
      patch :update
      get :sign_in
      post :login
      delete :sign_out
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/post.rb
class Post < ApplicationRecord
  has_rich_text :hello

  validates :title, presence: true
  validates :serial, uniqueness: true

  belongs_to :board
  belongs_to :user
  has_many :comments
  has_one_attached :photo

  before_create :create_serial

  def display_username
    if user.nil?
      "-"
    else
      user.account
    end
  end

  private
  def create_serial
    self.serial = serial_generator(10)
  end

  def serial_generator(n)
    [*'a'..'z', *'A'..'Z', *0..9].sample(n).join
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_board, only: [:new, :create]
  before_action :authenticate_user!, except: [:show]

  def show
    @post = Post.find(params[:id])
    @comment = @post.comments.new
    @comments = @post.comments.order(id: :desc)
  end

  def new
    @post = @board.posts.new
  end

  def create
    @post = @board.posts.new(post_params)

    if @post.save
      # 寄信
      # SendmailJob.set(wait: 10.seconds).perform_later(@post)
      redirect_to @board, notice: '文章新增成功'
    else
      render :new
    end
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])

    if @post.update(post_params)
      redirect_to @post, notice: '文章更新成功'
    else
      render :edit
    end
  end

  private

  def post_params
    params.require(:post)
          .permit(:title, :content, :photo, :hello)
          .merge(user: current_user)
  end

  def find_board
    @board = Board.find(params[:board_id])
  end
end

app/views/posts/edit.html.erb
<h1>編輯文章</h1>

<%= form_with(model: @post, local: true) do |form| %>

  <div class="fields">
    <%= form.label :title, "標題" %>
    <%= form.text_field :title %>
  </div>

  <div class="fields">
    <%= form.label :content, "內文" %>
    <%= form.text_area :content %>
  </div>

  <%= form.submit %>
<% end %>

app/views/posts/new.html.erb
<h1>新增文章</h1>

<%= form_with(model: @post, url: board_posts_path, local: true) do |form| %>

  <div class="fields">
    <%= form.label :title, "標題" %>
    <%= form.text_field :title %>
  </div>

  <div class="fields">
    <%= form.label :content, "內文" %>
    <%= form.text_area :content %>
  </div>

  <div class="fields">
    <%= form.label :hello, "內文" %>
    <%= form.rich_text_area :hello %>
  </div>

  <div class="fields">
    <%= form.label :photo, "附件" %>
    <%= form.file_field :photo %>
  </div>

  <%= form.submit %>
<% end %>

app/views/posts/show.html.erb
<section class="post">
<ul class="header">
  <li>
    <div>
      <span>作者</span>
      <span><%= @post.user.account %></span>
    </div>
    <div>
      <span>看板</span>
      <span><%= @post.board.title %></span>
    </div>
  </li>
  <li>
    <span>標題</span>
    <span><%= @post.title %></span>
  </li>
  <li>
    <span>時間</span>
    <span><%= @post.created_at %></span>
  </li>
</ul>
<hr>

<p>
  <%= @post.content %>
  <br>
  <%= @post.hello %>
  <br>
  <%= image_tag @post.photo.variant(resize_to_limit: [500, 500]) if @post.photo.attached? %>
</p>

<%= form_with(model: @comment, url: post_comments_path(@post)) do |form| %>
 <%= form.text_field :content %>
 <%= form.submit "送出" %>
<% end %>
<hr>
<ul>
<% @comments.each do |comment| %>
  <li><%= comment.content %></li>
<% end %>
</ul>
</section>